
CREATE TABLE IF NOT EXISTS users(
id  SERIAL PRIMARY KEY ,
username VARCHAR(45) NOT NULL,
email VARCHAR(45) NOT NULL,
password VARCHAR(200) NOT NULL,
name VARCHAR(45) NOT NULL,
cover_picture VARCHAR(100), 
profile_picture VARCHAR(100),
city VARCHAR(45) ,
website VARCHAR(45) 
);


CREATE TABLE IF NOT EXISTS posts(
id  SERIAL PRIMARY KEY,
description VARCHAR(200),
image VARCHAR(45),
user_id SERIAL NOT NULL,
FOREIGN KEY(user_id) REFERENCES users(id)
ON DELETE CASCADE 
ON UPDATE CASCADE  
);


CREATE TABLE IF NOT EXISTS comments(
id  SERIAL PRIMARY KEY,
description VARCHAR(200),
created_at timestamp NOT NULL,
user_id SERIAL NOT NULL REFERENCES users(id) ON DELETE CASCADE 
ON UPDATE CASCADE ,
post_id SERIAL NOT NULL  REFERENCES posts(id) ON DELETE CASCADE 
ON UPDATE CASCADE 
);

CREATE TABLE IF NOT EXISTS stories(
id  SERIAL PRIMARY KEY,
image_url VARCHAR(200) NOT NULL,
user_id SERIAL NOT NULL,
FOREIGN KEY(user_id) REFERENCES users(id)
ON DELETE CASCADE 
ON UPDATE CASCADE 
);


CREATE TABLE IF NOT EXISTS relationships(
id  SERIAL PRIMARY KEY,
follower_user_id SERIAL NOT NULL REFERENCES users(id)
ON DELETE CASCADE ON UPDATE CASCADE ,
followed_user_id SERIAL NOT NULL REFERENCES users(id)
ON DELETE CASCADE ON UPDATE CASCADE 

);


CREATE TABLE IF NOT EXISTS likes(
id  SERIAL PRIMARY KEY,
user_id SERIAL NOT NULL REFERENCES users(id)
ON DELETE CASCADE ON UPDATE CASCADE ,
post_id SERIAL NOT NULL REFERENCES posts(id)
ON DELETE CASCADE ON UPDATE CASCADE 
);